---
- name: Upgrade
  hosts: all
  remote_user: herman
  become: yes
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Upgrade APT to the latest packages
      apt:
        upgrade: dist

    - name: Remove useless packages
      apt:
        autoclean: yes

    - name: Remove useless dependencies
      apt:
        autoremove: yes
